version: "3.9"
services:
    bot:
        build: 
          context: ./bot
        depends_on:
          - database
        deploy:
          replicas: 1
          restart_policy:
            condition: on-failure
            delay: 60s
        env_file:
          - database.env
        environment:
          - DBHOST=database
          - PYTHONUNBUFFERED=1
        networks:
          - bot_net
    
    database:
        image: 'postgres:latest'
        env_file:
          - database.env
        environment:
          - POSTGRES_HOST_AUTH_METHOD=scram-sha-256
        volumes:
          - ./db-data/:/var/lib/postgresql/data/
        command: postgres -c listen_addresses='*'
        networks:
          - bot_net



networks:
  bot_net:
    driver: bridge